// cookie-manager/react/src/lib/components/Disclaimer/Disclaimer.tsx
import { DEFAULT_DISCLAIMER_CONFIG } from '@core/constants'
import type { DisclaimerConfiguration, Theme } from '@core/types'
import { Button } from '..'
import { parseThemeColors } from '@lib/app/parseStyles'
import './Disclaimer.css'

interface DisclaimerProps {
	configuration?: DisclaimerConfiguration
	theme?: Theme
	allowCookies: () => void
	declineCookies: () => void
}

export function Disclaimer({
	configuration = {},
	theme,
	allowCookies,
	declineCookies
}: DisclaimerProps): React.JSX.Element {
	const { title, body, policyUrl, policyText, acceptButtonText, rejectButtonText } = {
		...DEFAULT_DISCLAIMER_CONFIG,
		...configuration
	}
	const styles = parseThemeColors(theme)

	return (
		<div id="skcm-cookie-disclaimer" style={styles}>
			<div id="skcm-cookie-disclaimer__body">
				{title && <h6 id="skcm-title">{title}</h6>}
				<p id="skcm-body">
					{body}
					<a href={policyUrl} target="_blank" rel="noopener noreferrer">
						<span id="skcm-link__span">{policyText}</span>
					</a>
				</p>
			</div>
			<div id="skcm-cookie-disclaimer__buttons">
				<Button onClick={allowCookies} id="skcm-cookie-disclaimer__buttons--allow">
					{acceptButtonText}
				</Button>
				<Button onClick={declineCookies} id="skcm-cookie-disclaimer__buttons--reject">
					{rejectButtonText}
				</Button>
			</div>
		</div>
	)
}

// src/components/Disclaimer.svelte
<script lang="ts">
	import { DEFAULT_DISCLAIMER_CONFIG } from '$lib/constants';
	import type { DisclaimerConfiguration } from '$lib/types';
	import { Button } from './';

	export let configuration: DisclaimerConfiguration;
	export let allowCookies: () => void = () => {};
	export let declineCookies: () => void = () => {};
</script>

<div id="skcm-banner">
	<div>
		<h6>{configuration?.title ?? DEFAULT_DISCLAIMER_CONFIG.title}</h6>
		<p>
			{configuration?.body ?? DEFAULT_DISCLAIMER_CONFIG.body}
			<a href={configuration?.policyUrl ?? DEFAULT_DISCLAIMER_CONFIG.policyUrl} target="_blank"
				><span>{configuration?.policyText ?? DEFAULT_DISCLAIMER_CONFIG.policyText}</span></a
			>
		</p>
	</div>
	<div class="button-wrapper">
		<Button onClick={allowCookies}
			>{configuration?.acceptButtonText ?? DEFAULT_DISCLAIMER_CONFIG.acceptButtonText}</Button
		>
		<Button onClick={declineCookies}
			>{configuration?.rejectButtonText ?? DEFAULT_DISCLAIMER_CONFIG.rejectButtonText}
		</Button>
	</div>
</div>

<style type="text/scss">
	#skcm-banner {
		position: fixed;
		padding: 2rem 1.5rem 1rem 1.5rem;
		border-radius: 6px;
		background-color: $skcm-light;
		max-width: 100vw;
		bottom: 0;
		right: 0;
		border-radius: 0;
		z-index: 99999;
		@media (min-width: 640px) {
			max-width: 425px;
			bottom: 2.625rem;
			right: 3rem;
			border-radius: 6px;
		}
	}
</style>
