// cookie-manager/sveltekit/src/lib/components/Disclaimer.svelte
<script lang="ts">
	import { DEFAULT_DISCLAIMER_CONFIG, DEFAULT_THEME_COLORS } from '$core/constants'
	import type { DisclaimerConfiguration, Theme } from '$core/types'
	import { getInlineStyle } from '$core/utils'
	import { Button } from './'

	export let configuration: DisclaimerConfiguration = {}
	export let theme: Theme = DEFAULT_THEME_COLORS
	export let allowCookies: () => void = () => {}
	export let declineCookies: () => void = () => {}

	let style: string = ''

	$: ({ title, body } = configuration)
	$: style = getInlineStyle(theme)
</script>

<div id="skcm-cookie-disclaimer" {style}>
	<div id="skcm-cookie-disclaimer__body">
		{#if title}
			<h6 id="skcm-title">
				{title}
			</h6>
		{/if}
		<p id="skcm-body">
			{body ?? DEFAULT_DISCLAIMER_CONFIG.body}
			<a
				href={configuration?.policyUrl ?? DEFAULT_DISCLAIMER_CONFIG.policyUrl}
				target="_blank"
				rel="noopener noreferrer"
				><span id="skcm-link__span"
					>{configuration?.policyText ?? DEFAULT_DISCLAIMER_CONFIG.policyText}</span
				></a
			>
		</p>
	</div>
	<div id="skcm-cookie-disclaimer__buttons">
		<Button onClick={allowCookies} id="skcm-cookie-disclaimer__buttons--allow"
			>{configuration?.acceptButtonText ?? DEFAULT_DISCLAIMER_CONFIG.acceptButtonText}</Button
		>
		<Button onClick={declineCookies} id="skcm-cookie-disclaimer__buttons--reject"
			>{configuration?.rejectButtonText ?? DEFAULT_DISCLAIMER_CONFIG.rejectButtonText}
		</Button>
	</div>
</div>

<style lang="scss">
	#skcm-cookie-disclaimer {
		position: fixed;
		padding: 2rem 1.5rem 1rem 1.5rem;
		border-radius: 6px;
		background-color: var(--light);
		max-width: 100vw;
		bottom: 0;
		right: 0;
		border-radius: 0;
		z-index: 99999;
		@media (min-width: 640px) {
			max-width: 425px;
			bottom: 2.625rem;
			right: 3rem;
			border-radius: 6px;
		}
	}
</style>

// cookie-manager/react/src/lib/components/Disclaimer/Disclaimer.tsx
// import { useEffect, useState } from 'react'
import { DEFAULT_DISCLAIMER_CONFIG } from '@core/constants'
import type { DisclaimerConfiguration, Theme } from '@core/types'
// import { getInlineStyle } from '@core/utils'
import { Button } from '..'
import './Disclaimer.css'

interface DisclaimerProps {
	configuration?: DisclaimerConfiguration
	theme?: Theme
	allowCookies: () => void
	declineCookies: () => void
}

export function Disclaimer({
	configuration = {},
	allowCookies,
	declineCookies
}: DisclaimerProps): React.JSX.Element {
	// const [style, setStyle] = useState<string>('')
	const { title, body, policyUrl, policyText, acceptButtonText, rejectButtonText } = {
		...DEFAULT_DISCLAIMER_CONFIG,
		...configuration
	}

	// useEffect(() => {
	// 	setStyle(getInlineStyle(theme))
	// }, [theme])

	return (
		<div id="skcm-cookie-disclaimer">
			<div id="skcm-cookie-disclaimer__body">
				{title && <h6 id="skcm-title">{title}</h6>}
				<p id="skcm-body">
					{body}
					<a href={policyUrl} target="_blank" rel="noopener noreferrer">
						<span id="skcm-link__span">{policyText}</span>
					</a>
				</p>
			</div>
			<div id="skcm-cookie-disclaimer__buttons">
				<Button onClick={allowCookies} id="skcm-cookie-disclaimer__buttons--allow">
					{acceptButtonText}
				</Button>
				<Button onClick={declineCookies} id="skcm-cookie-disclaimer__buttons--reject">
					{rejectButtonText}
				</Button>
			</div>
		</div>
	)
}
