// src/lib/components/CookieManager.svelte
<script lang="ts">
	/* eslint-disable @typescript-eslint/no-unsafe-argument */
	import { page } from '$app/stores'
	import { initializeServices, updatePathGA } from '$lib/app/services'
	import { initConfiguredServices, showCookieDisclaimer } from '$lib/app/store'
	import { SKCMConfiguration, SupportedService } from '$lib/app/types'
	import {
		hasAllNeededNecessaryCookies,
		isServiceEnabled,
		submitNecessaryCookies
	} from '$lib/app/utils'
	import { onMount } from 'svelte'
	import { Disclaimer } from './'

	export let configuration: SKCMConfiguration

	$: ({ googleAnalyticsUniversalId, googleAnalytics4Id, customNecessaryCookies, adCookiesEnabled } =
		configuration?.services ?? {})

	// TODO: improve this
	$: if ($page?.url.pathname) {
		if (isServiceEnabled(SupportedService.GoogleAnalyticsUniversal)) {
			updatePathGA(googleAnalyticsUniversalId, $page.url.pathname)
		} else {
			if (isServiceEnabled(SupportedService.GoogleAnalytics4)) {
				updatePathGA(googleAnalytics4Id, $page.url.pathname)
			}
		}
	}

	onMount(() => {
		initConfiguredServices(
			googleAnalyticsUniversalId,
			googleAnalytics4Id,
			customNecessaryCookies,
			adCookiesEnabled
		)
		if (hasAllNeededNecessaryCookies()) {
			initializeServices()
		} else {
			showCookieDisclaimer.set(true)
		}
	})

	function handleSubmitNecessaryCookies(value: 'true' | 'false'): void {
		submitNecessaryCookies(value)
		if (value === 'true') {
			initializeServices()
		}
		showCookieDisclaimer.set(false)
	}

	function allowCookies(): void {
		handleSubmitNecessaryCookies('true')
	}

	function declineCookies(): void {
		handleSubmitNecessaryCookies('false')
	}
</script>

{#if $showCookieDisclaimer}
	<Disclaimer
		{allowCookies}
		{declineCookies}
		configuration={configuration?.disclaimer}
		theme={configuration?.theme}
	/>
{/if}

// cookie-manager/react/src/lib/components/CookieManager/CookieManager.tsx
import { useEffect } from 'react'
import type { Service, ServiceCookie, SKCMConfiguration } from '@core/types'
import { Disclaimer } from '..'
import { useCookieManagerContext } from '@lib/app/context'
import {
	hasAllNeededNecessaryCookies,
	initConfiguredServices,
	submitNecessaryCookies
} from '@core/services'
import { useManageServices } from '@lib/app/hooks'

interface CookieManagerProps {
	configuration: SKCMConfiguration
}

export function CookieManager({ configuration }: CookieManagerProps): React.JSX.Element {
	const {
		setConfiguredServices,
		setNecessaryCookies,
		necessaryCookies,
		configuredServices,
		showCookieDisclaimer,
		setShowCookieDisclaimer
	} = useCookieManagerContext()
	const { initializeServices } = useManageServices()

	const {
		googleAnalyticsUniversalId,
		googleAnalytics4Id,
		customNecessaryCookies,
		adCookiesEnabled
	} = configuration?.services ?? {}

	useEffect(() => {
		// eslint-disable-next-line no-console
		console.log('CookieManager: useEffect')
		function onServicesInitialized(services: Service[], cookies: ServiceCookie[]): void {
			setConfiguredServices(services)
			setNecessaryCookies(cookies)
		}
		initConfiguredServices({
			googleAnalyticsUniversalId,
			googleAnalytics4Id,
			customNecessaryCookies,
			adCookiesEnabled,
			onServicesInitialized
		})

		const canInitializeServices = hasAllNeededNecessaryCookies(necessaryCookies)

		if (canInitializeServices) {
			initializeServices()
		} else {
			setShowCookieDisclaimer(true)
		}
		// eslint-disable-next-line no-console
		console.log('CookieManager: useEffect end', { canInitializeServices, showCookieDisclaimer })
	}, [necessaryCookies])

	const handleSubmitNecessaryCookies = (value: 'true' | 'false') => {
		submitNecessaryCookies(value, configuredServices, necessaryCookies, setConfiguredServices)
		if (value === 'true') {
			initializeServices()
		}
		setShowCookieDisclaimer(false)
	}

	const allowCookies = () => {
		handleSubmitNecessaryCookies('true')
	}

	const declineCookies = () => {
		handleSubmitNecessaryCookies('false')
	}

	return (
		<>
			{showCookieDisclaimer && (
				<Disclaimer
					allowCookies={allowCookies}
					declineCookies={declineCookies}
					configuration={configuration?.disclaimer}
					theme={configuration?.theme}
				/>
			)}
		</>
	)
}

export default CookieManager
